# Dockerfile.frontend
FROM node:20-alpine

WORKDIR /app

# Copiar solo el package.json primero
COPY frontend/package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de los archivos del frontend
COPY frontend/ .

# Puerto expuesto
EXPOSE 5173

# Comando para iniciar la aplicación en desarrollo
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]