"""add production order table

Revision ID: 054459747655
Revises: 3609a3e64564
Create Date: 2026-07-02 17:26:35.451422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '054459747655'
down_revision: Union[str, Sequence[str], None] = '3609a3e64564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('bom_id', sa.BigInteger(), nullable=False),
    sa.Column('planned_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('produced_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('schedule_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['bom.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_consumption',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('production_order_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lot.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_output',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('production_order_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lot.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('product_type', postgresql.ENUM('BASE_BEER', 'PACKAGED', 'KEG', name='products_types'), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey'))
    )
    op.create_table('inputs_entries_items',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('inputs_entries_items_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_entry', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_input', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('expire_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_entry'], ['inputs_entries.id'], name='inputs_entries_items_id_entry_fkey'),
    sa.ForeignKeyConstraint(['id_input'], ['inputs.id'], name='inputs_entries_items_id_input_fkey'),
    sa.PrimaryKeyConstraint('id', name='inputs_entries_items_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('inputs_inventory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_entry_item', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_entry_item'], ['inputs_entries_items.id'], name=op.f('inputs_inventory_id_entry_item_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inputs_inventory_pkey'))
    )
    op.create_table('inputs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('minimum_stock', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('inputs_pkey')),
    sa.UniqueConstraint('name', 'brand', 'category', name=op.f('uq_input_identity'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('inputs_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_supplier', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('document_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('inputs_entries_pkey'))
    )
    # ### end Alembic commands ###
