"""update_input_entries_tables

Revision ID: 209adda9cd7a
Revises: 50be19c72b15
Create Date: 2026-03-19 13:15:34.169889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '209adda9cd7a'
down_revision: Union[str, Sequence[str], None] = '50be19c72b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputs_entries', sa.Column('reception_number', sa.String(length=255), nullable=False))
    op.add_column('inputs_entries', sa.Column('supplier', sa.String(length=255), nullable=False))
    op.add_column('inputs_entries', sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('inputs_entries', sa.Column('description', sa.String(length=500), nullable=True))
    op.alter_column('inputs_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'inputs_entries', ['reception_number'])
    op.drop_column('inputs_entries', 'document_number')
    op.drop_column('inputs_entries', 'id_supplier')
    op.add_column('inputs_entries_items', sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('inputs_entries_items', sa.Column('comment', sa.String(length=500), nullable=True))
    op.alter_column('inputs_entries_items', 'expire_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('inputs_inventory', sa.Column('id_input', sa.Integer(), nullable=False))
    op.add_column('inputs_inventory', sa.Column('initial_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('inputs_inventory', sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('inputs_inventory', sa.Column('expire_date', sa.Date(), nullable=False))
    op.add_column('inputs_inventory', sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'inputs_inventory', 'inputs', ['id_input'], ['id'])
    op.drop_column('inputs_inventory', 'updated_at')
    op.drop_column('inputs_inventory', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputs_inventory', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('inputs_inventory', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inputs_inventory', type_='foreignkey')
    op.drop_column('inputs_inventory', 'last_updated')
    op.drop_column('inputs_inventory', 'expire_date')
    op.drop_column('inputs_inventory', 'unit_cost')
    op.drop_column('inputs_inventory', 'initial_amount')
    op.drop_column('inputs_inventory', 'id_input')
    op.alter_column('inputs_entries_items', 'expire_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('inputs_entries_items', 'comment')
    op.drop_column('inputs_entries_items', 'unit_cost')
    op.add_column('inputs_entries', sa.Column('id_supplier', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('inputs_entries', sa.Column('document_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inputs_entries', type_='unique')
    op.alter_column('inputs_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('inputs_entries', 'description')
    op.drop_column('inputs_entries', 'total_cost')
    op.drop_column('inputs_entries', 'supplier')
    op.drop_column('inputs_entries', 'reception_number')
    # ### end Alembic commands ###
