"""update modelos bom and bom_line

Revision ID: 2dee8b06ae79
Revises: 054459747655
Create Date: 2026-07-09 22:08:52.608548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dee8b06ae79'
down_revision: Union[str, Sequence[str], None] = '054459747655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom', sa.Column('quantity', sa.Numeric(precision=14, scale=6), nullable=False))
    op.add_column('bom', sa.Column('uom_id', sa.Integer(), nullable=False))
    op.alter_column('bom', 'valid_from',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('bom', 'valid_to',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.create_foreign_key(None, 'bom', 'uom', ['uom_id'], ['id'])
    op.drop_column('bom_line', 'scrap_factor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom_line', sa.Column('scrap_factor', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bom', type_='foreignkey')
    op.alter_column('bom', 'valid_to',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('bom', 'valid_from',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('bom', 'uom_id')
    op.drop_column('bom', 'quantity')
    # ### end Alembic commands ###
