"""add beer table

Revision ID: 3609a3e64564
Revises: 35312fa99b28
Create Date: 2026-06-27 19:24:31.739610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3609a3e64564'
down_revision: Union[str, Sequence[str], None] = '35312fa99b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beer',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('style', sa.String(length=255), nullable=False),
    sa.Column('abv', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('ibu', sa.Integer(), nullable=False),
    sa.Column('fermentation_days', sa.Integer(), nullable=False),
    sa.Column('conditioning_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beer')
    # ### end Alembic commands ###
