"""eliminación del atributo 'scrap_factor' de la tabla 'bom_line'

Revision ID: 363389249863
Revises: 35312fa99b28
Create Date: 2026-06-26 14:33:01.873638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363389249863'
down_revision: Union[str, Sequence[str], None] = '35312fa99b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bom_line', 'scrap_factor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom_line', sa.Column('scrap_factor', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
