"""crear inventario de insumos

Revision ID: 42296d0b9eb5
Revises: c94bd4fa8b8d
Create Date: 2026-01-26 03:05:02.732538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42296d0b9eb5'
down_revision: Union[str, Sequence[str], None] = 'c94bd4fa8b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inputs_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_supplier', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('document_number', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inputs_entries_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_entry', sa.Integer(), nullable=False),
    sa.Column('id_input', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_entry'], ['inputs_entries.id'], ),
    sa.ForeignKeyConstraint(['id_input'], ['inputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inputs_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_entry_item', sa.Integer(), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_entry_item'], ['inputs_entries_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inputs_inventory')
    op.drop_table('inputs_entries_items')
    op.drop_table('inputs_entries')
    # ### end Alembic commands ###
