"""add_input_movements_table

Revision ID: a1b2c3d4e5f6
Revises: 42296d0b9eb5
Create Date: 2026-03-16 13:12:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '42296d0b9eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input_movements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('input_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['input_id'], ['inputs.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_check_constraint('ck_input_movements_event_type', 'input_movements', "event_type IN ('CREATED', 'UPDATED')")
    op.create_index('ix_input_movements_input_id', 'input_movements', ['input_id'])
    op.create_index('ix_input_movements_occurred_at', 'input_movements', ['occurred_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_input_movements_occurred_at', table_name='input_movements')
    op.drop_index('ix_input_movements_input_id', table_name='input_movements')
    op.drop_constraint('ck_input_movements_event_type', table_name='input_movements', type_='check')
    op.drop_table('input_movements')
    # ### end Alembic commands ###
