"""init schema

Revision ID: b8e7ddcfbe16
Revises: 
Create Date: 2026-05-03 00:37:01.293093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e7ddcfbe16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('item_type',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('uom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('uom_type', sa.String(length=20), nullable=False),
    sa.Column('factor_to_base', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'host', name='user_roles'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('item_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('base_uom_id', sa.Integer(), nullable=False),
    sa.Column('is_stockable', sa.Boolean(), nullable=False),
    sa.Column('is_batch_tracked', sa.Boolean(), nullable=False),
    sa.Column('min_stock_level', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('is_manufacturable', sa.Boolean(), nullable=False),
    sa.Column('is_purchasable', sa.Boolean(), nullable=False),
    sa.Column('is_sellable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['base_uom_id'], ['uom.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('supply_category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supply')
    op.drop_table('item')
    op.drop_table('users')
    op.drop_table('uom')
    op.drop_table('item_type')
    op.drop_table('brand')
    # ### end Alembic commands ###
