"""add_packaging_supply

Revision ID: d6ad6fe087ad
Revises: a606a4ebf4f7
Create Date: 2026-07-09 16:24:30.814020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6ad6fe087ad'
down_revision: Union[str, Sequence[str], None] = 'a606a4ebf4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packaging_supply',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('packaging_type', sa.String(length=255), nullable=False),
    sa.Column('material', sa.String(length=255), nullable=False),
    sa.Column('capacity_ml', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.drop_column('supply_entry_order', 'canceled_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supply_entry_order', sa.Column('canceled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_table('packaging_supply')
    # ### end Alembic commands ###
