"""Add cancellation fields to inputs_entries

Revision ID: dad0fe7a2474
Revises: 209adda9cd7a
Create Date: 2026-03-21 14:24:25.192782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad0fe7a2474'
down_revision: Union[str, Sequence[str], None] = '209adda9cd7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.add_column('inputs_entries', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # Agregar status como nullable primero
    op.add_column('inputs_entries', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('inputs_entries', sa.Column('annulled_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('inputs_entries', sa.Column('annulment_reason', sa.Text(), nullable=True))
    
    # Actualizar registros existentes con status 'active'
    op.execute("UPDATE inputs_entries SET status = 'active' WHERE status IS NULL")
    
    # Ahora hacer el campo NOT NULL
    op.alter_column('inputs_entries', 'status', nullable=False)
    
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('inputs_entries', 'annulment_reason')
    op.drop_column('inputs_entries', 'annulled_at')
    op.drop_column('inputs_entries', 'status')
    op.drop_column('inputs_entries', 'updated_at')
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
