"""añadir restriccion unica a name, brand y category

Revision ID: e061fba93203
Revises: c94bd4fa8b8d
Create Date: 2026-02-06 15:45:27.913900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e061fba93203'
down_revision: Union[str, Sequence[str], None] = 'c94bd4fa8b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_input_identity', 'inputs', ['name', 'brand', 'category'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_input_identity', 'inputs', type_='unique')
    # ### end Alembic commands ###
