"""change bom valid_from and valid_to from Date to TIMESTAMP

Revision ID: e7d129883e7a
Revises: 363389249863
Create Date: 2026-06-26 17:08:29.671186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d129883e7a'
down_revision: Union[str, Sequence[str], None] = '363389249863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bom', 'valid_from',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('bom', 'valid_to',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bom', 'valid_to',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('bom', 'valid_from',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
